### ISSUE TITLE
Is there a post on your blog describing how this works?

### ISSUE THREAD

**Issue by kozross** [lemire/sparsebitmap#3]
I know I can read the source code and all, but a higher-level, 'algorithmic' description would help me port this to a language I can work with. If this is based on a publication, that'd be even better.

**Comment by lemire** [comment]
@kozross 

What are the languages you can work with?

**Comment by lemire** [comment]
@kozross 

As for your specific question... I can't recall advertising this library much at all.

**Comment by kozross** [comment]
C or Haskell, ideally. I found this by following a link from [a different post of yours][1] while investigating SIMD and bitvector/bitmap stuff in general.

[1]: https://lemire.me/blog/2012/10/23/when-is-a-bitmap-faster-than-an-integer-list/

**Comment by lemire** [comment]
Ok. So, in C:

* https://github.com/RoaringBitmap/CRoaring (this is thoroughly documented)
* https://github.com/lemire/cbitset

In Haskell

* https://github.com/thsutton/rawr (no idea whether it is any good)
